# Site settings
title: Somay Jain
email: somayjain@gmail.com
description: "A senior-year computer science undergrad from IIIT Hyderabad. Have a keen interest in high performance computing and it's blend with computer graphics and vision. Having worked on HFOSS projects for the past 2 years, enthusiastic about open source software development."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
